name: fastmri
dependencies:
  - python>=3.9
  - pip
  - h5py=3.7.0
  - numpy=1.23.5
  - scikit-image=0.19.2
  - torchvision>=0.8.1
  - runstats>=1.8.0
  - h5py>=2.10.0
  - PyYAML>=5.3.1
  - torchmetrics>=0.5.1
  - pandas>=1.3.4
  - scipy>=1.6.2
  - pip:
      - torch>=1.8.0
      - pytorch_lightning>=1.4
      - opencv-python==4.5.4.60
      - tensorboard==2.18.0
      - ismrmrd-1.14.1
      - requests-2.32.3
